name: my_first_workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"
      - name: Show Os Details
        run: |
          uname -a
          lsb_release -a || true
          cat /etc/os-release
